insert into alien values(101,'Max','python');
insert into alien values(102,'Andi','java');
insert into alien values(103,'Carol','sql');
insert into alien values(104,'Sarah','python');
insert into alien values(105,'Joey','javascript');
insert into alien values(106,'Julie','python');
insert into alien values(107,'Alvaro','ruby');
insert into alien values(108,'Diego','sql');
insert into alien values(109,'Chewi','java');